import type { ProfCertification, ProfPhoto, ProfPrice, ProfProfile, ProfSport, ProfSpot, Review } from "./schema";
import type { ProfWithRelations } from "./relations.schema";

const now = new Date("2025-01-01T00:00:00.000Z");

const profiles: ProfProfile[] = [
    {
        id: "1",
        userId: "user-1",
        firstName: "Jean",
        lastName: "Dupont",
        bio: "Jean Dupont est un passionné de sports nautiques avec plus de 10 ans d'expérience en tant que moniteur de kitesurf et de windsurf. Il a enseigné à des centaines d'élèves, des débutants aux compétiteurs, et est reconnu pour sa pédagogie et sa patience.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Leucate",
        region: "Occitanie",
        phone: null,
        contactEmail: "jean.dupont@example.com",
        contactVisibility: "email_only",
        responseTime: "same_day",
        websites: null,
        equipmentProvided: true,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "2",
        userId: "user-2",
        firstName: "Marie",
        lastName: "Curie",
        bio: "Marie Curie est une professeure de sport passionnée, avec plus de 8 ans d'expérience dans l'enseignement des sports aquatiques. Elle est appréciée pour sa patience et son dévouement.",
        photoUrl: null,
        isVerified: false,
        isPublished: true,
        city: "Gruissan",
        region: "Occitanie",
        phone: "0123456789",
        contactEmail: "marie.curie@example.com",
        contactVisibility: "phone_email",
        responseTime: "within_24h",
        websites: null,
        equipmentProvided: false,
        equipmentNote: null,
        languages: JSON.stringify(["Français"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "3",
        userId: "user-3",
        firstName: "Pierre",
        lastName: "Martin",
        bio: "Pierre Martin est un instructeur de sports nautiques expérimenté, spécialisé dans le wingfoil. Avec plus de 15 ans d'expérience, il est reconnu pour sa pédagogie et sa capacité à adapter ses cours en fonction des besoins de chaque élève.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Erquy",
        region: "Bretagne",
        phone: null,
        contactEmail: null,
        contactVisibility: "phone_email",
        responseTime: "2h",
        websites: null,
        equipmentProvided: true,
        equipmentNote: "Matériel fourni pour les débutants",
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "4",
        userId: "user-4",
        firstName: "Sophie",
        lastName: "Durand",
        bio: "Sophie Durand est une instructrice de sports nautiques passionnée, avec plus de 10 ans d'expérience dans l'enseignement du kitesurf et du windsurf. Sophie est appréciée pour sa patience et son dévouement.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Leucate",
        region: "Occitanie",
        phone: "0123456789",
        contactEmail: "sophie.durand@example.com",
        contactVisibility: "phone_email",
        responseTime: "30min",
        websites: null,
        equipmentProvided: false,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "Español"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "5",
        userId: "user-5",
        firstName: "Lucas",
        lastName: "Bernard",
        bio: "Lucas Bernard est moniteur de kitesurf depuis 12 ans, basé à Arcachon. Ancien compétiteur, il transmet sa passion avec enthousiasme et adapte ses cours à tous les profils, des enfants aux adultes.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Arcachon",
        region: "Nouvelle-Aquitaine",
        phone: null,
        contactEmail: "lucas.bernard@example.com",
        contactVisibility: "email_only",
        responseTime: "within_24h",
        websites: null,
        equipmentProvided: true,
        equipmentNote: "Matériel complet fourni pour les débutants",
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "6",
        userId: "user-6",
        firstName: "Camille",
        lastName: "Moreau",
        bio: "Camille Moreau est une passionnée de wingfoil et de windsurf, monitrice diplômée depuis 7 ans. Elle enseigne sur les spots de la côte basque et est particulièrement appréciée pour sa bonne humeur.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Hendaye",
        region: "Nouvelle-Aquitaine",
        phone: null,
        contactEmail: "camille.moreau@example.com",
        contactVisibility: "phone_email",
        responseTime: "2h",
        websites: null,
        equipmentProvided: true,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "Español", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "7",
        userId: "user-7",
        firstName: "Antoine",
        lastName: "Lefebvre",
        bio: "Antoine Lefebvre est un moniteur de windsurf chevronné avec 20 ans d'expérience. Basé en Bretagne, il est spécialisé dans les cours pour les niveaux intermédiaires et avancés, avec une approche très technique.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Brest",
        region: "Bretagne",
        phone: null,
        contactEmail: null,
        contactVisibility: "phone_email",
        responseTime: "same_day",
        websites: null,
        equipmentProvided: false,
        equipmentNote: null,
        languages: JSON.stringify(["Français"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "8",
        userId: "user-8",
        firstName: "Léa",
        lastName: "Petit",
        bio: "Léa Petit est monitrice de kitesurf et de wingfoil depuis 5 ans. Jeune et dynamique, elle excelle dans l'enseignement aux débutants et crée une ambiance conviviale pour progresser rapidement.",
        photoUrl: null,
        isVerified: false,
        isPublished: true,
        city: "La Tranche-sur-Mer",
        region: "Pays de la Loire",
        phone: null,
        contactEmail: "lea.petit@example.com",
        contactVisibility: "email_only",
        responseTime: "within_24h",
        websites: null,
        equipmentProvided: true,
        equipmentNote: "Location de matériel possible",
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "9",
        userId: "user-9",
        firstName: "Hugo",
        lastName: "Simon",
        bio: "Hugo Simon est un instructeur de sports de glisse avec 14 ans d'expérience. Spécialiste du wingfoil, il propose des stages intensifs pour progresser rapidement sur le lac de Mimizan.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Mimizan",
        region: "Nouvelle-Aquitaine",
        phone: null,
        contactEmail: null,
        contactVisibility: "phone_email",
        responseTime: "30min",
        websites: null,
        equipmentProvided: true,
        equipmentNote: null,
        languages: JSON.stringify(["Français"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "10",
        userId: "user-10",
        firstName: "Isabelle",
        lastName: "Rousseau",
        bio: "Isabelle Rousseau est professeure de kitesurf et de windsurf depuis 9 ans. Formée en Australie, elle apporte une approche internationale à ses cours et parle couramment anglais et allemand.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "La Palmyre",
        region: "Nouvelle-Aquitaine",
        phone: null,
        contactEmail: "isabelle.rousseau@example.com",
        contactVisibility: "email_only",
        responseTime: "within_24h",
        websites: null,
        equipmentProvided: false,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "English", "Deutsch"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "11",
        userId: "user-11",
        firstName: "Maxime",
        lastName: "Laurent",
        bio: "Maxime Laurent est moniteur de windsurf et de kitesurf depuis 11 ans, basé sur la côte méditerranéenne. Ancien champion régional de windsurf, il partage sa passion avec une pédagogie rigoureuse.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Montpellier",
        region: "Occitanie",
        phone: null,
        contactEmail: null,
        contactVisibility: "phone_email",
        responseTime: "2h",
        websites: null,
        equipmentProvided: true,
        equipmentNote: "Matériel haut de gamme fourni",
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "12",
        userId: "user-12",
        firstName: "Clara",
        lastName: "Fontaine",
        bio: "Clara Fontaine est une monitrice polyvalente spécialisée dans le wingfoil et le kitesurf. Après 6 ans d'enseignement en Méditerranée, elle est connue pour sa pédagogie douce et efficace.",
        photoUrl: null,
        isVerified: false,
        isPublished: true,
        city: "Sète",
        region: "Occitanie",
        phone: null,
        contactEmail: "clara.fontaine@example.com",
        contactVisibility: "phone_email",
        responseTime: "same_day",
        websites: null,
        equipmentProvided: true,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "Italiano"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "13",
        userId: "user-13",
        firstName: "Nicolas",
        lastName: "Garnier",
        bio: "Nicolas Garnier est instructeur de kitesurf depuis 13 ans sur la côte normande. Il est particulièrement apprécié pour ses cours en petits groupes et son expertise des conditions venteuses du nord.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Deauville",
        region: "Normandie",
        phone: null,
        contactEmail: null,
        contactVisibility: "phone_email",
        responseTime: "within_24h",
        websites: null,
        equipmentProvided: false,
        equipmentNote: null,
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "14",
        userId: "user-14",
        firstName: "Amandine",
        lastName: "Chevalier",
        bio: "Amandine Chevalier est monitrice de windsurf depuis 8 ans, basée à Hyères. Elle propose des cours adaptés à tous les niveaux et est certifiée par la Fédération Française de Voile.",
        photoUrl: null,
        isVerified: true,
        isPublished: true,
        city: "Hyères",
        region: "Provence-Alpes-Côte d'Azur",
        phone: null,
        contactEmail: "amandine.chevalier@example.com",
        contactVisibility: "email_only",
        responseTime: "30min",
        websites: null,
        equipmentProvided: true,
        equipmentNote: "Combinaisons fournies",
        languages: JSON.stringify(["Français", "English"]),
        createdAt: now,
        updatedAt: now,
    },
];

const sports: ProfSport[] = [
    { id: "s1", profId: "1", sport: "kitesurf", acceptedLevels: JSON.stringify(["beginner", "intermediate"]) },
    { id: "s2", profId: "1", sport: "windsurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s3", profId: "2", sport: "kitesurf", acceptedLevels: JSON.stringify(["beginner"]) },
    { id: "s4", profId: "3", sport: "wingfoil", acceptedLevels: JSON.stringify(["intermediate", "advanced"]) },
    { id: "s5", profId: "4", sport: "kitesurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s6", profId: "4", sport: "windsurf", acceptedLevels: JSON.stringify(["beginner", "intermediate"]) },
    { id: "s7", profId: "5", sport: "kitesurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s8", profId: "6", sport: "wingfoil", acceptedLevels: JSON.stringify(["beginner", "intermediate"]) },
    { id: "s9", profId: "6", sport: "windsurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s10", profId: "7", sport: "windsurf", acceptedLevels: JSON.stringify(["intermediate", "advanced"]) },
    { id: "s11", profId: "8", sport: "kitesurf", acceptedLevels: JSON.stringify(["beginner"]) },
    { id: "s12", profId: "8", sport: "wingfoil", acceptedLevels: JSON.stringify(["beginner"]) },
    { id: "s13", profId: "9", sport: "wingfoil", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s14", profId: "10", sport: "kitesurf", acceptedLevels: JSON.stringify(["intermediate", "advanced"]) },
    { id: "s15", profId: "10", sport: "windsurf", acceptedLevels: JSON.stringify(["beginner", "intermediate"]) },
    { id: "s16", profId: "11", sport: "windsurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s17", profId: "11", sport: "kitesurf", acceptedLevels: JSON.stringify(["intermediate", "advanced"]) },
    { id: "s18", profId: "12", sport: "wingfoil", acceptedLevels: JSON.stringify(["beginner", "intermediate"]) },
    { id: "s19", profId: "12", sport: "kitesurf", acceptedLevels: JSON.stringify(["beginner"]) },
    { id: "s20", profId: "13", sport: "kitesurf", acceptedLevels: JSON.stringify(["all"]) },
    { id: "s21", profId: "14", sport: "windsurf", acceptedLevels: JSON.stringify(["all"]) },
];

const certifications: ProfCertification[] = [
    { id: "c1", profId: "1", type: "BPJEPS", year: 2015, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c2", profId: "1", type: "IKO L3", year: 2018, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c3", profId: "2", type: "BPJEPS", year: 2017, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c4", profId: "3", type: "BPJEPS", year: 2010, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c5", profId: "3", type: "IKO L3", year: 2014, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c6", profId: "4", type: "BPJEPS", year: 2016, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c7", profId: "5", type: "BPJEPS", year: 2013, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c8", profId: "5", type: "IKO L2", year: 2015, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c9", profId: "6", type: "BPJEPS", year: 2019, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c10", profId: "7", type: "BPJEPS", year: 2006, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c11", profId: "8", type: "IKO L1", year: 2021, fileName: null, fileUrl: null, status: "pending", createdAt: now, updatedAt: now },
    { id: "c12", profId: "9", type: "BPJEPS", year: 2012, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c13", profId: "10", type: "BPJEPS", year: 2017, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c14", profId: "10", type: "IKO L3", year: 2020, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c15", profId: "11", type: "BPJEPS", year: 2014, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c16", profId: "12", type: "BPJEPS", year: 2020, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c17", profId: "13", type: "BPJEPS", year: 2013, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c18", profId: "14", type: "BPJEPS", year: 2018, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
    { id: "c19", profId: "14", type: "FFVoile", year: 2019, fileName: null, fileUrl: null, status: "verified", createdAt: now, updatedAt: now },
];

const prices: ProfPrice[] = [
    { id: "p1", profId: "1", description: "Cours individuel", duration: "1h", priceEur: 50, displayOrder: 0 },
    { id: "p2", profId: "1", description: "Stage 3 jours", duration: "3j", priceEur: 120, displayOrder: 1 },
    { id: "p3", profId: "2", description: "Cours individuel", duration: "1h", priceEur: 40, displayOrder: 0 },
    { id: "p4", profId: "3", description: "Cours individuel", duration: "1h", priceEur: 60, displayOrder: 0 },
    { id: "p5", profId: "4", description: "Cours individuel", duration: "1h", priceEur: 55, displayOrder: 0 },
    { id: "p6", profId: "4", description: "Cours en groupe (4 pers.)", duration: "1h", priceEur: 30, displayOrder: 1 },
    { id: "p7", profId: "5", description: "Cours individuel", duration: "1h", priceEur: 65, displayOrder: 0 },
    { id: "p8", profId: "5", description: "Stage 5 jours", duration: "5j", priceEur: 280, displayOrder: 1 },
    { id: "p9", profId: "6", description: "Cours individuel", duration: "1h", priceEur: 55, displayOrder: 0 },
    { id: "p10", profId: "6", description: "Cours en groupe (3 pers.)", duration: "1h", priceEur: 35, displayOrder: 1 },
    { id: "p11", profId: "7", description: "Cours individuel", duration: "1h", priceEur: 70, displayOrder: 0 },
    { id: "p12", profId: "8", description: "Cours individuel", duration: "1h30", priceEur: 45, displayOrder: 0 },
    { id: "p13", profId: "9", description: "Stage intensif", duration: "2j", priceEur: 150, displayOrder: 0 },
    { id: "p14", profId: "9", description: "Cours individuel", duration: "1h", priceEur: 60, displayOrder: 1 },
    { id: "p15", profId: "10", description: "Cours individuel", duration: "1h", priceEur: 55, displayOrder: 0 },
    { id: "p16", profId: "11", description: "Cours individuel", duration: "1h", priceEur: 65, displayOrder: 0 },
    { id: "p17", profId: "11", description: "Stage 3 jours", duration: "3j", priceEur: 160, displayOrder: 1 },
    { id: "p18", profId: "12", description: "Cours individuel", duration: "1h", priceEur: 50, displayOrder: 0 },
    { id: "p19", profId: "13", description: "Cours individuel", duration: "1h", priceEur: 60, displayOrder: 0 },
    { id: "p20", profId: "13", description: "Cours en groupe (4 pers.)", duration: "1h", priceEur: 35, displayOrder: 1 },
    { id: "p21", profId: "14", description: "Cours individuel", duration: "1h", priceEur: 50, displayOrder: 0 },
    { id: "p22", profId: "14", description: "Stage week-end", duration: "2j", priceEur: 130, displayOrder: 1 },
];

const spots: ProfSpot[] = [
    { id: "sp1", profId: "1", name: "Leucate Plage", isPrimary: true, displayOrder: 0 },
    { id: "sp2", profId: "1", name: "Port-la-Nouvelle", isPrimary: false, displayOrder: 1 },
    { id: "sp3", profId: "2", name: "Gruissan Plage", isPrimary: true, displayOrder: 0 },
    { id: "sp4", profId: "3", name: "Erquy", isPrimary: true, displayOrder: 0 },
    { id: "sp5", profId: "3", name: "Saint-Cast-le-Guildo", isPrimary: false, displayOrder: 1 },
    { id: "sp6", profId: "4", name: "Leucate Plage", isPrimary: true, displayOrder: 0 },
    { id: "sp7", profId: "5", name: "Arcachon", isPrimary: true, displayOrder: 0 },
    { id: "sp8", profId: "5", name: "Lacanau", isPrimary: false, displayOrder: 1 },
    { id: "sp9", profId: "6", name: "Hendaye Plage", isPrimary: true, displayOrder: 0 },
    { id: "sp10", profId: "6", name: "Saint-Jean-de-Luz", isPrimary: false, displayOrder: 1 },
    { id: "sp11", profId: "7", name: "Brest", isPrimary: true, displayOrder: 0 },
    { id: "sp12", profId: "8", name: "La Tranche-sur-Mer", isPrimary: true, displayOrder: 0 },
    { id: "sp13", profId: "9", name: "Mimizan Plage", isPrimary: true, displayOrder: 0 },
    { id: "sp14", profId: "10", name: "La Palmyre", isPrimary: true, displayOrder: 0 },
    { id: "sp15", profId: "10", name: "Royan", isPrimary: false, displayOrder: 1 },
    { id: "sp16", profId: "11", name: "Palavas-les-Flots", isPrimary: true, displayOrder: 0 },
    { id: "sp17", profId: "12", name: "Sète", isPrimary: true, displayOrder: 0 },
    { id: "sp18", profId: "13", name: "Deauville", isPrimary: true, displayOrder: 0 },
    { id: "sp19", profId: "13", name: "Courseulles-sur-Mer", isPrimary: false, displayOrder: 1 },
    { id: "sp20", profId: "14", name: "Hyères", isPrimary: true, displayOrder: 0 },
    { id: "sp21", profId: "14", name: "Almanarre", isPrimary: false, displayOrder: 1 },
];

const reviews: Review[] = [
    { id: "r1", profId: "1", riderId: null, riderName: "Thomas L.", riderLevel: "beginner", rating: 5, body: "Excellent moniteur, très patient et pédagogue. Je recommande vivement !", createdAt: now },
    { id: "r2", profId: "1", riderId: null, riderName: "Camille R.", riderLevel: "intermediate", rating: 4, body: "Bonne expérience, Jean sait s'adapter au niveau de chaque élève.", createdAt: now },
    { id: "r3", profId: "2", riderId: null, riderName: "Lucas M.", riderLevel: "beginner", rating: 5, body: "Marie est une super prof, j'ai adoré mes cours !", createdAt: now },
    { id: "r4", profId: "3", riderId: null, riderName: "Élodie P.", riderLevel: "intermediate", rating: 5, body: "Pierre est un expert, ses cours sont très bien structurés.", createdAt: now },
    { id: "r5", profId: "3", riderId: null, riderName: "Nathan B.", riderLevel: "advanced", rating: 4, body: "Très bon niveau technique, des conseils précieux pour progresser.", createdAt: now },
    { id: "r6", profId: "4", riderId: null, riderName: "Inès G.", riderLevel: "beginner", rating: 5, body: "Sophie est fantastique, j'ai progressé très vite grâce à elle.", createdAt: now },
    { id: "r7", profId: "5", riderId: null, riderName: "Julien F.", riderLevel: "beginner", rating: 5, body: "Lucas est un super moniteur, très à l'écoute et encourageant. Je suis accro au kitesurf !", createdAt: now },
    { id: "r8", profId: "5", riderId: null, riderName: "Sarah K.", riderLevel: "intermediate", rating: 4, body: "Très bon stage, j'ai beaucoup progressé. Les explications sont claires et précises.", createdAt: now },
    { id: "r9", profId: "6", riderId: null, riderName: "Marc D.", riderLevel: "beginner", rating: 5, body: "Camille est une monitrice exceptionnelle, j'ai adoré mes cours de wingfoil avec elle !", createdAt: now },
    { id: "r10", profId: "7", riderId: null, riderName: "Florian T.", riderLevel: "intermediate", rating: 4, body: "Antoine est très technique, j'ai beaucoup appris sur les subtilités du windsurf.", createdAt: now },
    { id: "r11", profId: "7", riderId: null, riderName: "Céline M.", riderLevel: "advanced", rating: 5, body: "Le meilleur instructeur de windsurf que j'ai eu, des conseils très pointus pour progresser.", createdAt: now },
    { id: "r12", profId: "8", riderId: null, riderName: "Théo B.", riderLevel: "beginner", rating: 5, body: "Léa est géniale, elle met vraiment à l'aise les débutants. Super ambiance !", createdAt: now },
    { id: "r13", profId: "9", riderId: null, riderName: "Romain S.", riderLevel: "intermediate", rating: 5, body: "Le stage intensif avec Hugo est incroyable, deux jours suffisent pour vraiment décoller en wingfoil.", createdAt: now },
    { id: "r14", profId: "10", riderId: null, riderName: "Audrey P.", riderLevel: "beginner", rating: 4, body: "Isabelle est très professionnelle et parle très bien anglais, idéal pour les cours mixtes.", createdAt: now },
    { id: "r15", profId: "11", riderId: null, riderName: "Bastien R.", riderLevel: "intermediate", rating: 5, body: "Maxime est passionné et ça se ressent, ses cours sont toujours de grande qualité.", createdAt: now },
    { id: "r16", profId: "12", riderId: null, riderName: "Laure C.", riderLevel: "beginner", rating: 4, body: "Clara est très patiente et pédagogue, idéale pour débuter le wingfoil en douceur.", createdAt: now },
    { id: "r17", profId: "13", riderId: null, riderName: "Victor H.", riderLevel: "beginner", rating: 5, body: "Nicolas maîtrise parfaitement les conditions normandes, ses cours sont adaptés même par vent fort.", createdAt: now },
    { id: "r18", profId: "14", riderId: null, riderName: "Margot V.", riderLevel: "all", rating: 5, body: "Amandine est formidable, j'ai adoré mes cours à Hyères. Le spot est magnifique !", createdAt: now },
];

const photos: ProfPhoto[] = [
    // Jean Dupont (kitesurf / windsurf) — 4 photos, triggers "+2 PHOTOS" overlay
    { id: "ph1", profId: "1", key: "profs/1/gallery/ph1.jpg", url: "https://images.unsplash.com/photo-1768639400733-45d6cead226a?w=1200&q=80&auto=format&fit=crop", displayOrder: 0, createdAt: now },
    { id: "ph2", profId: "1", key: "profs/1/gallery/ph2.jpg", url: "https://images.unsplash.com/photo-1601144378611-48eb4755a8c8?w=1200&q=80&auto=format&fit=crop", displayOrder: 1, createdAt: now },
    { id: "ph3", profId: "1", key: "profs/1/gallery/ph3.jpg", url: "https://images.unsplash.com/photo-1691156803402-4c55c9cb6bea?w=1200&q=80&auto=format&fit=crop", displayOrder: 2, createdAt: now },
    { id: "ph4", profId: "1", key: "profs/1/gallery/ph4.jpg", url: "https://images.unsplash.com/photo-1733757276564-8762b8d63498?w=1200&q=80&auto=format&fit=crop", displayOrder: 3, createdAt: now },
    // Sophie Durand (kitesurf / windsurf) — 2 photos
    { id: "ph5", profId: "4", key: "profs/4/gallery/ph5.jpg", url: "https://images.unsplash.com/photo-1710161158760-9274dca99c26?w=1200&q=80&auto=format&fit=crop", displayOrder: 0, createdAt: now },
    { id: "ph6", profId: "4", key: "profs/4/gallery/ph6.jpg", url: "https://images.unsplash.com/photo-1731969114548-9d8140e7dca3?w=1200&q=80&auto=format&fit=crop", displayOrder: 1, createdAt: now },
    // Antoine Lefebvre (windsurf) — 3 photos
    { id: "ph7", profId: "7", key: "profs/7/gallery/ph7.jpg", url: "https://images.unsplash.com/photo-1731969114548-9d8140e7dca3?w=1200&q=80&auto=format&fit=crop", displayOrder: 0, createdAt: now },
    { id: "ph8", profId: "7", key: "profs/7/gallery/ph8.jpg", url: "https://images.unsplash.com/photo-1710161158760-9274dca99c26?w=1200&q=80&auto=format&fit=crop", displayOrder: 1, createdAt: now },
    { id: "ph9", profId: "7", key: "profs/7/gallery/ph9.jpg", url: "https://images.unsplash.com/photo-1601144378611-48eb4755a8c8?w=1200&q=80&auto=format&fit=crop", displayOrder: 2, createdAt: now },

    { id: "ph10", profId: "2", key: "profs/2/gallery/ph10.jpg", url: "https://images.unsplash.com/photo-1601144378611-48eb4755a8c8?w=1200&q=80&auto=format&fit=crop", displayOrder: 0, createdAt: now },
];

const buildProfWithRelations = (profile: ProfProfile): ProfWithRelations => ({
    ...profile,
    sports: sports.filter((s) => s.profId === profile.id),
    spots: spots.filter((s) => s.profId === profile.id),
    prices: prices.filter((p) => p.profId === profile.id),
    certifications: certifications.filter((c) => c.profId === profile.id),
    photos: photos.filter((ph) => ph.profId === profile.id),
    reviews: reviews.filter((r) => r.profId === profile.id),
    reports: [],
});

export const getProfs = async (): Promise<ProfWithRelations[]> => {
    await new Promise((resolve) => setTimeout(resolve, 500));
    return profiles.map(buildProfWithRelations);
};

export const getProf = async (id: string): Promise<ProfWithRelations | undefined> => {
    await new Promise((resolve) => setTimeout(resolve, 500));
    const profile = profiles.find((p) => p.id === id);
    return profile ? buildProfWithRelations(profile) : undefined;
};
